// lipi-stronghold-key-bridge — StrongholdKeyBridge.kt
//
// SKELETON. Status: Phase 0 contract. No Kotlin code has
// been compiled or run yet — this file documents the
// shape the future Mac/Linux session will fill in. The
// future session should also add a corresponding
// `StrongholdKeyBridgeTest.kt` under
// `android/app/src/test/kotlin/lipi/stronghold/`.
//
// See `docs/plugins/lipi-stronghold-key-bridge/README.md`
// for the full design contract + D-186 for the rationale.

package lipi.stronghold

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey

/**
 * Bridge between Rust (`secrets_stronghold.rs`) and the
 * Android Keystore.
 *
 * The flow on every Rust call to `loadKey()`:
 *   1. Get the singleton `AndroidKeyStore` instance.
 *   2. If `lipi_stronghold_master` doesn't exist, generate
 *      it (AES-256/GCM, no user auth required, no padding).
 *   3. Initialise a `Cipher` ("AES/GCM/NoPadding") in
 *      ENCRYPT_MODE with the key. The Keystore generates
 *      a fresh random IV and returns it as part of the
 *      cipher params.
 *   4. Encrypt a known 32-byte zero plaintext under the
 *      key.
 *   5. Return the ciphertext (IV || ciphertext, 60 bytes:
 *      12-byte IV + 32-byte plaintext + 16-byte GCM tag).
 *
 * The Rust side SHA-256s the 60-byte ciphertext and uses
 * the first 32 bytes of the digest as the `KeyProvider`
 * key. The AES-GCM IV is fresh every call (the Keystore
 * generates it), so the digest is also fresh every call —
 * but the snapshot file is encrypted ONCE per write and
 * decrypted ONCE per read, and both use the same Keystore
 * key (which is deterministic across launches), so the
 * round-trip works.
 *
 * Why SHA-256 of the ciphertext (not the raw ciphertext)?
 *   - The ciphertext depends on the hardware-backed key,
 *     so the digest is uniformly random. Knowing the
 *     digest reveals nothing about the key.
 *   - The digest is exactly 32 bytes — the length
 *     `KeyProvider::try_from` requires.
 *
 * Trade-off accepted (per D-186):
 *   - Clearing app data wipes the Keystore key (and the
 *     snapshot file). The user re-enters their AI provider
 *     keys. Same trade-off 1Password / Bitwarden / most
 *     other Android password managers make.
 *   - No `setUserAuthenticationRequired` — the UX cost of
 *     a per-launch biometric prompt is high for an IDE
 *     the developer opens dozens of times per day, and
 *     the security benefit is small (a locked phone is
 *     already protected by the lock screen). A v1.1
 *     follow-up could add a Settings toggle for biometric
 *     unlock.
 */
object StrongholdKeyBridge {
    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEY_ALIAS = "lipi_stronghold_master"
    private const val KEY_SIZE_BITS = 256
    private const val ZERO_PLAINTEXT_SIZE_BYTES = 32

    /**
     * The JNI entry point. The Rust side calls this via
     * the mangled name
     *   `Java_lipi_stronghold_StrongholdKeyBridge_loadKey`
     * (auto-generated by `javac` from the `external`
     * declaration). Returns the 60-byte
     * "SHA-256 input material" (12 IV + 32 ciphertext +
     * 16 GCM tag). Throws `KeyStoreException` if the
     * Keystore is unavailable (very rare — broken device
     * or custom ROM with Keystore stripped).
     */
    @JvmStatic
    external fun loadKey(): ByteArray

    init {
        // The native lib `liblipi_stronghold_key_bridge.so`
        // is built from `secrets_stronghold_key_bridge.rs`
        // (the Rust JNI implementation) and bundled into
        // the APK by Tauri's Android build pipeline. The
        // exact cargo layout (separate cdylib crate vs.
        // a `cdylib` target in the main crate) is a
        // future-session decision — see the README §9.
        System.loadLibrary("lipi_stronghold_key_bridge")
    }

    /**
     * The actual implementation. Called by the Rust side
     * via JNI (or, in tests, directly).
     *
     * This is a `fun` not a `suspend fun` — the Android
     * Keystore APIs are synchronous. The Rust side blocks
     * on the JNI call (which blocks on this function).
     * Typical call duration: 5-20ms (Keystore key lookup
     * is the slow part; the AES-GCM encrypt itself is
     * sub-millisecond on hardware-backed devices).
     *
     * Must be called on a thread with a Looper (typically
     * the main thread). The Android Keystore
     * `KeyStoreException: AndroidKeyStore not initialized`
     * is thrown if this is called on a background thread
     * without a Looper. The Rust side ensures this by
     * calling from a `tauri::command` handler (which runs
     * on the main thread by default in Tauri 2.x).
     */
    @JvmStatic
    fun loadKeyImpl(): ByteArray {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        val secretKey = getOrCreateKey(keyStore)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        // cipher.iv is set by init() — a fresh random 12 bytes
        // generated by the Keystore (or, on weaker devices, by
        // the platform crypto provider).
        val iv = cipher.iv
        val ciphertextWithTag = cipher.doFinal(ByteArray(ZERO_PLAINTEXT_SIZE_BYTES))
        // Prepend IV to ciphertext. Result: 12 + 48 = 60 bytes.
        // (The last 16 bytes of ciphertextWithTag are the GCM
        // authentication tag, which the Keystore appends
        // automatically.)
        return iv + ciphertextWithTag
    }

    /**
     * Look up `lipi_stronghold_master` in the Keystore;
     * generate it on first use. The key is scoped to the
     * app UID, so it's automatically wiped when the user
     * clears app data (the `Stronghold` snapshot file is
     * wiped at the same time, so no decryption failures).
     */
    private fun getOrCreateKey(keyStore: KeyStore): SecretKey {
        keyStore.getKey(KEY_ALIAS, null)?.let { return it as SecretKey }
        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE_PROVIDER,
        )
        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setKeySize(KEY_SIZE_BITS)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setRandomizedEncryptionRequired(true)
            // No setUserAuthenticationRequired — see class
            // doc for the trade-off. A v1.1 follow-up
            // could add it behind a Settings toggle.
            .build()
        generator.init(spec)
        return generator.generateKey()
    }
}
