//! Phase 2: offline-license signing + verification (see
//! `docs/plans/prod-p2-licensing-design.md` for the full design
//! and `HANDOFF.md §9.24` for the per-phase writeup).
//!
//! # The shape of a license
//!
//! A Lipi license is a JWS-style compact signed document:
//!
//! ```text
//! LIP1.<base64url(payload)>.<base64url(signature)>
//! ```
//!
//! `LIP1` is a fixed magic prefix (Lipi license v1). The
//! dot-separated format is the JWS compact serialization
//! (RFC 7515). A real key looks like:
//!
//! ```text
//! LIP1.eyJmb3JtYXQiOiJsaXBpLWxpY2Vuc2UtdjEiLCJwbGFuIjoieWVhcmx5I...<truncated>..<signature>
//! ```
//!
//! The payload is a JSON object with the shape of
//! `LicensePayload` (see below). The signature is an Ed25519
//! signature (64 bytes) over the bytes
//! `"LIP1." || base64url(payload)` (the JWS "signing input").
//!
//! # Verification
//!
//! The verification is fully offline. There is no server
//! round-trip, no phone-home, no revocation list. The Rust
//! side embeds the production public key and the trial public
//! key as `const [u8; 32]` arrays; the signature is verified
//! against the appropriate key based on the context (paid
//! licenses are verified with the production key, trials with
//! the trial key). The match against the embedded public key
//! is the only cryptographic check.
//!
//! # Threat model
//!
//! The "no backend, ever" architectural rule (Decision #17)
//! means we cannot do online license validation. The trade-off
//! is:
//!
//! - A user who extracts the trial private key from the binary
//!   can generate fake trial licenses. The trial has a 14-day
//!   max `exp`, so the damage is bounded.
//! - A user who has a valid paid license can use it on multiple
//!   machines, but the machine fingerprint bind (`sub` claim)
//!   detects the second-machine install. The Rust side returns
//!   `LicenseStatus::Invalid` with `reason: "machine-mismatch"`,
//!   which the UI shows as "This license is for a different
//!   machine".
//! - A user who tampers with the keychain (e.g. overwrites the
//!   `license` entry with a self-signed payload) is caught on
//!   the next `license_get_status` call: the signature fails to
//!   verify, and the status returns `Unactivated`.
//!
//! The threats we don't try to defend against:
//!
//! - Debugger-driven bypass (a user who can attach a debugger
//!   to `lipi.exe` can patch out the verification).
//! - VM cloning (a user who clones a VM keeps the same
//!   hostname / username / MAC, so the fingerprint is the same;
//!   the license is shared). This is the same threat model as
//!   JetBrains / Sublime / every other desktop tool.
//!
//! # Crate choices
//!
//! - `ed25519-dalek` v2: Ed25519 signing + verification. Pure-
//!   Rust, no C deps, MSRV 1.65+.
//! - `sha2` v0.10: SHA-256 for the machine fingerprint. We
//!   hash `hostname || username || mac_address` and hex-encode
//!   the 32-byte digest.
//! - `base64` v0.22: JWS-style base64url encoding (no padding).
//! - `hostname` v0.4: Cross-platform hostname.
//! - `whoami` v1: Cross-platform OS username.
//! - `mac_address` v1: Cross-platform MAC address.
//!
//! See `docs/plans/prod-p2-licensing-design.md` "Crate choices"
//! for the full rationale.

use std::time::{SystemTime, UNIX_EPOCH};

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine as _;
use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};

// --- Embedded public keys -----------------------------------------
//
// The production public key and the trial public key are embedded
// as `const [u8; 32]` arrays (the 32 raw bytes of an Ed25519
// verifying key). The values are committed to the repo. The
// private keys are stored in the project lead's CI secret store
// and on an encrypted USB drive (not committed).
//
// To rotate the production key, generate a new Ed25519 keypair:
//
//     cargo run --bin gen_license_keypair
//
// and paste the printed public-key bytes over `PROD_PUBKEY`
// below, then store the printed 64-char hex string in the
// `TAURI_PROD_LICENSE_KEY_HEX` CI secret (or the project
// lead's offline backup). The trial key is rotated the same way
// (see `TRIAL_PUBKEY`).
//
// The `PROD_PUBKEY` below is the **production** keypair — the
// private half is held by the project lead, never committed. The
// previous value was a placeholder from the design phase; it
// was replaced on 2026-06-14 with a real key generated by
// `gen_license_keypair`. Any old license keys signed with the
// previous private key are now invalid. The trial keypair
// (`TRIAL_PUBKEY` + `TRIAL_PRIVKEY` below) is still a
// throwaway for auto-generated trial licenses; the trial
// private key is committed on purpose so every install gets the
// same `KID_TRIAL` signing behavior without needing a CI
// secret.
const PROD_PUBKEY: [u8; 32] = [
    0xbe, 0xdf, 0x69, 0x4e, 0x52, 0x4f, 0xc1, 0x49, 0xe6, 0x6c, 0xbc, 0x3b, 0xdb, 0xaf, 0x1a, 0xe3,
    0x96, 0x55, 0x77, 0xe1, 0xa2, 0xaf, 0x35, 0xc7, 0xdd, 0x0a, 0xc2, 0x61, 0x8d, 0x22, 0x26, 0xe5,
];
const TRIAL_PUBKEY: [u8; 32] = [
    0xbc, 0xc3, 0xf8, 0x65, 0x31, 0xb8, 0x70, 0x20, 0xba, 0x99, 0xe7, 0xbc, 0x0d, 0xfb, 0x04, 0x3d,
    0xf1, 0xe5, 0x57, 0x8a, 0xb7, 0x14, 0xc8, 0xc5, 0xa0, 0x6a, 0x56, 0x06, 0x0f, 0xc8, 0x1a, 0xa1,
];

// The trial private key (also embedded). This is the deliberate
// trade-off: a 14-day max `exp` bounds the worst case. The
// production private key is NOT embedded.
//
// To regenerate the trial keypair (same openssl incantation as
// PROD_PUBKEY above), the placeholder is:
const TRIAL_PRIVKEY: [u8; 32] = [
    0x6c, 0x68, 0x72, 0x6a, 0x29, 0x71, 0x74, 0x6e, 0x69, 0x65, 0x27, 0x60, 0x69, 0x74, 0x23, 0x3c,
    0x22, 0x3c, 0x70, 0x6a, 0x60, 0x70, 0x65, 0x3a, 0x77, 0x7f, 0x37, 0x76, 0x75, 0x65, 0x72, 0x76,
];

// --- Constants ----------------------------------------------------

/// The fixed magic prefix for a Lipi license. Matches the
/// JWS compact serialization format (header.payload.signature)
/// with a custom "header" of `LIP1`.
pub const LICENSE_PREFIX: &str = "LIP1";

/// The fixed format identifier in the payload. Future versions
/// (e.g. v2 with a "max machines" field) would use a different
/// format string; the parser rejects unknown formats.
pub const LICENSE_FORMAT_V1: &str = "lipi-license-v1";

/// The license "plan" values. The string is the value the user
/// sees in the UI ("Trial", "Monthly", "Yearly").
pub const PLAN_TRIAL: &str = "trial";
pub const PLAN_MONTHLY: &str = "monthly";
pub const PLAN_YEARLY: &str = "yearly";

/// Key-id values for the `LicensePayload.kid` field.
/// Identifies which pubkey to use to verify the
/// signature. The verifier dispatches on this value
/// (see `verify_license`).
///
/// - `KID_TRIAL` — the embedded trial pubkey
///   (`TRIAL_PUBKEY`). Used for auto-generated
///   trials.
/// - `KID_OFFLINE` — the embedded production
///   pubkey (`PROD_PUBKEY`). Used for
///   `LIP1...` keys from purchase emails
///   (signed by the project lead's
///   `sign_license` CLI).
/// - `KID_IAP_LOCAL` — the per-machine
///   Ed25519 pubkey stored in the keychain
///   (under `KEYCHAIN_USER_IAP_PUBKEY`).
///   Used for IAP-generated licenses
///   (signed with the per-machine privkey
///   generated on first IAP redemption).
///
/// Phase 4 introduced the `kid` field. Older
/// v0.0.x licenses (without `kid`) are treated
/// as `KID_TRIAL` by the verifier for
/// backward-compat (the original v0.0.x
/// license format was trial-only).
pub const KID_TRIAL: &str = "trial";
pub const KID_OFFLINE: &str = "offline";
pub const KID_IAP_LOCAL: &str = "iap-local";

/// The grace period (in seconds) after expiry. A license that
/// is past `exp` but within the grace period is `GracePeriod`,
/// not `Expired`. After the grace period elapses, the status
/// flips to `Expired` and the app hard-blocks the workspace
/// (Phase 3 wires the UI; Phase 2 just computes the status).
pub const GRACE_PERIOD_SECS: i64 = 7 * 24 * 60 * 60;

/// The trial duration (in seconds). Auto-generated on first run.
pub const TRIAL_DURATION_SECS: i64 = 14 * 24 * 60 * 60;

/// The OS keychain service name. Matches the convention in
/// `secrets.rs` (Decision #23 — the service name = the bundle
/// ID). The keychain namespaces by service, so a service rename
/// would not migrate existing entries.
pub(crate) const KEYCHAIN_SERVICE: &str = "app.lipi.ide";

/// `pub(crate)` accessor for the keychain service
/// name. The `iap_keypair` module re-uses the same
/// service for its per-machine IAP privkey +
/// pubkey entries, so they all live under the
/// same `app.lipi.ide` namespace.
#[allow(dead_code)] // The const is referenced from `iap_keypair::service_name` test.
pub(crate) fn keychain_service() -> &'static str {
    KEYCHAIN_SERVICE
}

/// The keychain user-name for the license key string.
/// We store the full `LIP1.payload.signature` key here;
/// the Rust side re-verifies the signature on every
/// `license_get_status` call (an Ed25519 verify is
/// microseconds, so the cost is negligible), so we
/// don't need a separate "last verified at" cache.
///
/// (A future optimisation could add a
/// `KEYCHAIN_USER_LAST_VERIFIED` keychain entry that
/// caches the verification result; the design doc
/// discusses it under "Persistence". We deferred
/// this because the verify is already cheap.)
const KEYCHAIN_USER_LICENSE: &str = "license";

/// Keychain username for the per-machine IAP private
/// key. 64 lowercase hex chars (32 bytes), generated
/// on first IAP redemption. Used by `iap_keypair`.
/// Private to this module; `iap_keypair` re-imports
/// it via a `pub(crate)` accessor in the same crate.
const KEYCHAIN_USER_IAP_PRIVKEY: &str = "iap-privkey";

/// Keychain username for the per-machine IAP public
/// key. 64 lowercase hex chars (32 bytes), the
/// Ed25519 pubkey corresponding to the privkey.
/// Used by `verify_license` to verify IAP-signed
/// licenses.
const KEYCHAIN_USER_IAP_PUBKEY: &str = "iap-pubkey";

/// `pub(crate)` accessors so the `iap_keypair` module
/// can read / write the IAP privkey + pubkey
/// keychain entries without re-declaring the
/// constants.
pub(crate) fn keychain_user_iap_privkey() -> &'static str {
    KEYCHAIN_USER_IAP_PRIVKEY
}

pub(crate) fn keychain_user_iap_pubkey() -> &'static str {
    KEYCHAIN_USER_IAP_PUBKEY
}

// --- The payload ---------------------------------------------------

/// The signed JSON payload. Serialised as compact JSON
/// (no whitespace, no indentation) before being base64url-
/// encoded. The Rust side derives `Serialize` + `Deserialize`
/// so the format is type-checked end to end.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LicensePayload {
    /// "lipi-license-v1" — fixed format identifier. The Rust
    /// side checks this on parse; a mismatched value is
    /// treated as "not a Lipi license".
    pub format: String,

    /// "trial" | "monthly" | "yearly". Drives the paywall /
    /// grace period / feature gating.
    pub plan: String,

    /// Unix timestamp when the license was issued.
    pub iat: i64,

    /// Unix timestamp when the license becomes valid.
    /// Almost always == iat.
    pub nbf: i64,

    /// Unix timestamp when the license expires.
    pub exp: i64,

    /// SHA-256 of hostname || username || mac_address,
    /// hex-encoded, 32 chars. The license is bound to this
    /// machine.
    pub sub: String,

    /// Random per-license id (16 random hex chars).
    pub jti: String,

    /// Key id — identifies which pubkey to use to
    /// verify the signature. One of `KID_TRIAL`,
    /// `KID_OFFLINE`, or `KID_IAP_LOCAL`. Optional
    /// for backward-compat with v0.0.x licenses
    /// (which predate the `kid` field); missing
    /// `kid` is treated as `KID_TRIAL` by the
    /// verifier.
    ///
    /// Phase 4 added this field. The IAP receipt
    /// validator sets it to `KID_IAP_LOCAL`; the
    /// project lead's `sign_license` CLI sets it
    /// to `KID_OFFLINE`; the auto-generated trial
    /// sets it to `KID_TRIAL`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kid: Option<String>,
}

impl LicensePayload {
    /// Validates the payload's *shape* (not the signature). A
    /// payload that fails shape-validation is rejected before
    /// the signature check, because the signature check is
    /// expensive in attacker-controlled inputs (a 1MB payload
    /// would take O(N) to verify; shape-validation caps the
    /// size).
    pub fn validate_shape(&self) -> Result<(), LicenseError> {
        if self.format != LICENSE_FORMAT_V1 {
            return Err(LicenseError::InvalidShape {
                detail: format!(
                    "unknown format {:?} (expected {:?})",
                    self.format, LICENSE_FORMAT_V1
                ),
            });
        }
        if self.plan != PLAN_TRIAL && self.plan != PLAN_MONTHLY && self.plan != PLAN_YEARLY {
            return Err(LicenseError::InvalidShape {
                detail: format!(
                    "unknown plan {:?} (expected one of {:?}, {:?}, {:?})",
                    self.plan, PLAN_TRIAL, PLAN_MONTHLY, PLAN_YEARLY
                ),
            });
        }
        if self.sub.len() != 64 || !self.sub.chars().all(|c| c.is_ascii_hexdigit()) {
            return Err(LicenseError::InvalidShape {
                detail: format!(
                    "sub {:?} is not 64 hex chars (SHA-256 of hostname||username||mac)",
                    self.sub
                ),
            });
        }
        if self.jti.len() > 64 || self.jti.is_empty() {
            return Err(LicenseError::InvalidShape {
                detail: format!("jti length {} is out of range (1..=64)", self.jti.len()),
            });
        }
        // The format / plan / jti strings are bounded by the
        // JSON spec; we don't add an additional length cap
        // because serde_json will fail to parse oversized
        // strings first. The 16-char cap on `format` is
        // implicit (the constant is "lipi-license-v1" = 15
        // chars; we'd notice a 1MB string in shape validation).
        if self.iat < 0 || self.nbf < 0 || self.exp < 0 {
            return Err(LicenseError::InvalidShape {
                detail: "timestamps must be non-negative".to_string(),
            });
        }
        if self.exp <= self.iat {
            return Err(LicenseError::InvalidShape {
                detail: format!("exp {} is not after iat {}", self.exp, self.iat),
            });
        }
        if let Some(kid) = &self.kid {
            if kid != KID_TRIAL && kid != KID_OFFLINE && kid != KID_IAP_LOCAL {
                return Err(LicenseError::InvalidShape {
                    detail: format!(
                        "unknown kid {:?} (expected one of {:?}, {:?}, {:?})",
                        kid, KID_TRIAL, KID_OFFLINE, KID_IAP_LOCAL
                    ),
                });
            }
        }
        Ok(())
    }
}

// --- The status ---------------------------------------------------

/// What the app reports to the UI. Mirrors the JSON shape the
/// JS side reads in `src/ipc/licensing.ts::LicenseStatusPayload`.
///
/// The `tag = "kind"` + `rename_all = "camelCase"` matches the
/// project's existing IPC error / payload convention (see
/// `src-tauri/src/secrets.rs` and `src/ipc/secrets.ts`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", tag = "kind")]
pub enum LicenseStatus {
    /// No license file in the keychain. The app should show
    /// the activation screen. The first call to
    /// `license_get_status` after install generates a 14-day
    /// trial and stores it; subsequent calls hit the trial.
    /// This variant is only returned for an explicit "never
    /// had a trial" state (e.g. after a `license_deactivate`
    /// call).
    Unactivated,

    /// License is valid and not expired. The payload's plan +
    /// exp are available.
    Active {
        plan: String,
        expires_at: i64,
        issued_at: i64,
        days_remaining: i64,
    },

    /// License is in the 7-day grace period after expiry.
    GracePeriod {
        plan: String,
        expired_at: i64,
        days_into_grace: i64,
    },

    /// License is past the grace period. The app should
    /// hard-block the workspace (Phase 3).
    Expired { plan: String, expired_at: i64 },

    /// License is on a trial. The plan is "trial", the
    /// expiry is 14 days from iat.
    Trial {
        expires_at: i64,
        days_remaining: i64,
    },

    /// License file is in the keychain but failed
    /// verification. The UI shows "License invalid" + the
    /// reason. Common reasons: signature mismatch (tampered),
    /// machine mismatch (different machine), expired (past
    /// the grace period and still failing verification), or
    /// malformed (the key string wasn't a valid JWS).
    Invalid { reason: String },
}

// --- Errors -------------------------------------------------------

/// Error type for the licensing module. Serialised to camelCase
/// JSON for the frontend. The `kind` is the IPC `tag`; the
/// `detail` is a human-readable message.
///
/// Each variant has a single `detail: String` field for
/// debuggability. The TS side reads `payload.kind` and
/// `payload.detail`.
///
/// The `InvalidShape` variant is internal-only (it's raised
/// before the signature is checked); the public-facing reason
/// is "malformed" (a 1MB payload, a non-JSON payload, a payload
/// that fails shape validation, all surface as "malformed" in
/// the public API).
#[derive(Debug, thiserror::Error, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind")]
pub enum LicenseError {
    #[error("invalid input: {detail}")]
    InvalidInput { detail: String },

    #[error("invalid shape: {detail}")]
    InvalidShape { detail: String },

    #[error("keychain unavailable: {detail}")]
    KeychainUnavailable { detail: String },

    #[error("keychain error: {detail}")]
    Platform { detail: String },

    /// The IAP-issued license references a per-machine
    /// pubkey (kid = "iap-local"), but the keychain
    /// entry is missing. This happens when the user
    /// has an IAP-generated license on a machine whose
    /// keychain has been wiped (e.g. OS reinstall,
    /// keychain corruption, new user account). The
    /// recovery is to re-run the IAP flow (the user's
    /// Apple / Microsoft subscription is unchanged).
    #[error("IAP-local pubkey missing from keychain: {detail}")]
    MissingLocalPubkey { detail: String },
}

impl From<keyring::Error> for LicenseError {
    fn from(e: keyring::Error) -> Self {
        match e {
            keyring::Error::NoEntry => LicenseError::Platform {
                detail: "no entry".to_string(),
            },
            keyring::Error::Ambiguous(_) => LicenseError::Platform {
                detail: "ambiguous entry".to_string(),
            },
            keyring::Error::BadEncoding(_) => LicenseError::Platform {
                detail: "bad encoding".to_string(),
            },
            other => LicenseError::KeychainUnavailable {
                detail: other.to_string(),
            },
        }
    }
}

// --- Signing + verification primitives ---------------------------

/// Sign a payload with the given secret key. The result is
/// the JWS-style compact form: `"LIP1." || base64url(payload_json)
/// || "." || base64url(signature)`.
///
/// This is exposed publicly so the offline `sign_license` CLI
/// tool (Phase 4) can call it. The trial-generation flow uses
/// it with the trial key (embedded as a const).
pub fn sign_payload(
    payload: &LicensePayload,
    secret_key: &[u8; 32],
) -> Result<String, LicenseError> {
    let key = SigningKey::from_bytes(secret_key);
    let payload_json = serde_json::to_vec(payload).map_err(|e| LicenseError::InvalidShape {
        detail: format!("serialise payload: {e}"),
    })?;
    let payload_b64 = URL_SAFE_NO_PAD.encode(&payload_json);
    let signing_input = format!("{LICENSE_PREFIX}.{payload_b64}");
    let signature = key.sign(signing_input.as_bytes());
    let signature_b64 = URL_SAFE_NO_PAD.encode(signature.to_bytes());
    Ok(format!("{signing_input}.{signature_b64}"))
}

/// Parse a license key string into the (payload, signature)
/// pair, validating the JWS shape. Returns `InvalidShape` on
/// any parse error. The signature is NOT verified here —
/// `verify_license` does that.
pub fn parse_key(key: &str) -> Result<(LicensePayload, Vec<u8>), LicenseError> {
    let key = key.trim();
    let mut parts = key.split('.');
    let prefix = parts.next().ok_or_else(|| LicenseError::InvalidShape {
        detail: "missing prefix segment".to_string(),
    })?;
    let payload_b64 = parts.next().ok_or_else(|| LicenseError::InvalidShape {
        detail: "missing payload segment".to_string(),
    })?;
    let signature_b64 = parts.next().ok_or_else(|| LicenseError::InvalidShape {
        detail: "missing signature segment".to_string(),
    })?;
    if parts.next().is_some() {
        return Err(LicenseError::InvalidShape {
            detail: "extra dot-separated segment".to_string(),
        });
    }
    if prefix != LICENSE_PREFIX {
        return Err(LicenseError::InvalidShape {
            detail: format!(
                "unknown prefix {:?} (expected {:?})",
                prefix, LICENSE_PREFIX
            ),
        });
    }
    let payload_json = URL_SAFE_NO_PAD
        .decode(payload_b64.as_bytes())
        .map_err(|e| LicenseError::InvalidShape {
            detail: format!("base64url-decode payload: {e}"),
        })?;
    let payload: LicensePayload =
        serde_json::from_slice(&payload_json).map_err(|e| LicenseError::InvalidShape {
            detail: format!("parse payload JSON: {e}"),
        })?;
    let signature = URL_SAFE_NO_PAD
        .decode(signature_b64.as_bytes())
        .map_err(|e| LicenseError::InvalidShape {
            detail: format!("base64url-decode signature: {e}"),
        })?;
    if signature.len() != 64 {
        return Err(LicenseError::InvalidShape {
            detail: format!("signature is {} bytes (expected 64)", signature.len()),
        });
    }
    payload.validate_shape()?;
    Ok((payload, signature))
}

/// Verify a license key. Returns the parsed `LicensePayload` on
/// success, or an `InvalidShape` on parse error. The signature
/// is verified against the appropriate embedded public key
/// based on the payload's `plan` field: a `"trial"` plan is
/// verified with the trial pubkey; everything else with the
/// production pubkey.
pub fn verify_license(key: &str) -> Result<LicensePayload, LicenseError> {
    verify_license_with_pubkey_resolver(key, resolve_pubkey_for_kid)
}

/// Verify a license using a custom pubkey resolver. The
/// default resolver (`resolve_pubkey_for_kid`) handles
/// `KID_TRIAL` + `KID_OFFLINE` (embedded pubkeys) and
/// `KID_IAP_LOCAL` (per-machine pubkey from the
/// keychain). Tests pass a stub resolver to bypass the
/// keychain.
pub fn verify_license_with_pubkey_resolver<F>(
    key: &str,
    resolve_pubkey: F,
) -> Result<LicensePayload, LicenseError>
where
    F: Fn(&str) -> Result<[u8; 32], LicenseError>,
{
    let (payload, signature_bytes) = parse_key(key)?;
    let kid = payload.kid.as_deref().unwrap_or(KID_TRIAL);
    let pubkey_bytes = resolve_pubkey(kid)?;
    let verifying_key =
        VerifyingKey::from_bytes(&pubkey_bytes).map_err(|e| LicenseError::InvalidShape {
            detail: format!("invalid pubkey for kid {kid:?}: {e}"),
        })?;
    let signature = Signature::from_bytes(signature_bytes.as_slice().try_into().map_err(|_| {
        LicenseError::InvalidShape {
            detail: "signature is not 64 bytes".to_string(),
        }
    })?);
    let payload_b64 = key
        .trim()
        .split('.')
        .nth(1)
        .ok_or_else(|| LicenseError::InvalidShape {
            detail: "missing payload segment after parse".to_string(),
        })?;
    let signing_input = format!("{LICENSE_PREFIX}.{payload_b64}");
    verifying_key
        .verify(signing_input.as_bytes(), &signature)
        .map_err(|_| LicenseError::InvalidShape {
            detail: format!("signature verification failed for kid {kid:?}"),
        })?;
    Ok(payload)
}

/// Default pubkey resolver. Maps a `kid` string to the
/// corresponding 32-byte pubkey. For embedded kids
/// (`KID_TRIAL`, `KID_OFFLINE`), returns the compiled-in
/// pubkey. For `KID_IAP_LOCAL`, reads the per-machine
/// pubkey from the keychain.
fn resolve_pubkey_for_kid(kid: &str) -> Result<[u8; 32], LicenseError> {
    match kid {
        KID_TRIAL => Ok(TRIAL_PUBKEY),
        KID_OFFLINE => Ok(PROD_PUBKEY),
        KID_IAP_LOCAL => crate::iap_keypair::load_iap_pubkey().ok_or(LicenseError::MissingLocalPubkey {
            detail: "the IAP-issued license is for this machine, but the per-machine pubkey is missing from the keychain. Re-run the IAP flow to regenerate the keypair.".to_string(),
        }),
        other => Err(LicenseError::InvalidShape {
            detail: format!("unknown kid {other:?}"),
        }),
    }
}

// --- Machine fingerprint ----------------------------------------

/// Compute this machine's fingerprint. The result is a
/// 32-character lowercase hex string (a SHA-256 of
/// `hostname || "\n" || username || "\n" || mac_address`).
///
/// The fingerprint is stable across reboots (the inputs don't
/// change on a single machine) and unique per machine
/// (collisions would require identical hostname + username +
/// MAC, which is essentially impossible).
pub fn machine_fingerprint() -> String {
    use sha2::{Digest, Sha256};

    let hostname = hostname::get()
        .ok()
        .and_then(|s| s.into_string().ok())
        .unwrap_or_else(|| "unknown-host".to_string());
    let username = whoami::username();
    let mac = mac_address::get_mac_address()
        .ok()
        .flatten()
        .map(|m| m.to_string())
        .unwrap_or_else(|| "unknown-mac".to_string());

    let mut hasher = Sha256::new();
    hasher.update(hostname.as_bytes());
    hasher.update(b"\n");
    hasher.update(username.as_bytes());
    hasher.update(b"\n");
    hasher.update(mac.as_bytes());
    let digest = hasher.finalize();
    hex_lower(&digest)
}

/// Lowercase hex encoding. We don't use the `hex` crate to keep
/// the dep tree minimal (the project already has `sha2` as a
/// transitive; adding `hex` would be a new dep for one
/// function).
fn hex_lower(bytes: &[u8]) -> String {
    const HEX: &[u8] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

// --- Time helpers -------------------------------------------------

/// Current Unix timestamp in seconds. Returns 0 if the system
/// clock is before the Unix epoch (impossible in practice;
/// handled defensively so we never panic on a corrupt clock).
pub fn now_unix_secs() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}

// --- Status derivation -------------------------------------------

/// Derive a `LicenseStatus` from a verified payload. The
/// `now` parameter is injected for testability (production
/// calls `derive_status(payload)` which calls `now_unix_secs()`
/// internally; tests can call `derive_status_at(payload, fake_now)`).
pub fn derive_status_at(payload: &LicensePayload, now: i64) -> LicenseStatus {
    // Check the not-before. A license whose `nbf` is in the
    // future is "not yet valid" — this is rare (a delayed
    // activation), but the spec allows it. We surface it as
    // `Invalid` with a clear reason rather than `Active`.
    if payload.nbf > now {
        return LicenseStatus::Invalid {
            reason: format!("not-yet-valid: nbf {} is in the future", payload.nbf),
        };
    }

    let seconds_remaining = payload.exp - now;

    if seconds_remaining > 0 {
        // License is active.
        let days_remaining = seconds_remaining / 86_400;
        if payload.plan == PLAN_TRIAL {
            LicenseStatus::Trial {
                expires_at: payload.exp,
                days_remaining,
            }
        } else {
            LicenseStatus::Active {
                plan: payload.plan.clone(),
                expires_at: payload.exp,
                issued_at: payload.iat,
                days_remaining,
            }
        }
    } else {
        // Past exp. Is it in the grace period?
        let seconds_into_grace = -seconds_remaining;
        if seconds_into_grace <= GRACE_PERIOD_SECS {
            let days_into_grace = seconds_into_grace / 86_400;
            LicenseStatus::GracePeriod {
                plan: payload.plan.clone(),
                expired_at: payload.exp,
                days_into_grace,
            }
        } else {
            LicenseStatus::Expired {
                plan: payload.plan.clone(),
                expired_at: payload.exp,
            }
        }
    }
}

/// Convenience: derive a status with the current time.
pub fn derive_status(payload: &LicensePayload) -> LicenseStatus {
    derive_status_at(payload, now_unix_secs())
}

// --- Trial generation --------------------------------------------

/// Generate a fresh trial license for this machine. The
/// payload is signed with the trial private key (embedded as
/// a const), and the result is a fully-formed `LIP1...`
/// license key string.
pub fn generate_trial_license() -> Result<(LicensePayload, String), LicenseError> {
    let now = now_unix_secs();
    let payload = LicensePayload {
        format: LICENSE_FORMAT_V1.to_string(),
        plan: PLAN_TRIAL.to_string(),
        iat: now,
        nbf: now,
        exp: now + TRIAL_DURATION_SECS,
        sub: machine_fingerprint(),
        jti: random_jti(),
        kid: Some(KID_TRIAL.to_string()),
    };
    payload.validate_shape()?;
    let key = sign_payload(&payload, &TRIAL_PRIVKEY)?;
    Ok((payload, key))
}

/// 16 random hex chars (64 bits of entropy). We use `getrandom`
/// (already a transitive dep) rather than pulling in `rand`.
fn random_jti() -> String {
    let mut bytes = [0u8; 8];
    let _ = getrandom::getrandom(&mut bytes);
    hex_lower(&bytes)
}

// --- Keychain wrappers -------------------------------------------

/// A process-wide cache of `keyring::Entry` handles, keyed by
/// user-name. Mirrors the pattern in `secrets.rs` (avoid
/// repeated Credential Manager lookups; the mock store is
/// per-Entry).
fn entry_cache(
) -> &'static std::sync::Mutex<std::collections::HashMap<String, std::sync::Arc<keyring::Entry>>> {
    use std::sync::OnceLock;
    static CACHE: OnceLock<
        std::sync::Mutex<std::collections::HashMap<String, std::sync::Arc<keyring::Entry>>>,
    > = OnceLock::new();
    CACHE.get_or_init(|| std::sync::Mutex::new(std::collections::HashMap::new()))
}

fn entry_for(user: &str) -> Result<std::sync::Arc<keyring::Entry>, LicenseError> {
    let mut cache = entry_cache().lock().map_err(|e| LicenseError::Platform {
        detail: format!("entry cache lock poisoned: {e}"),
    })?;
    if let Some(entry) = cache.get(user) {
        return Ok(entry.clone());
    }
    let entry = keyring::Entry::new(KEYCHAIN_SERVICE, user).map_err(LicenseError::from)?;
    let arc = std::sync::Arc::new(entry);
    cache.insert(user.to_string(), arc.clone());
    Ok(arc)
}

/// `pub(crate)` accessor for the keychain entry
/// cache. The `iap_keypair` module uses the same
/// cached entry handles to avoid repeated
/// Credential Manager lookups for the per-machine
/// privkey / pubkey. Errors are mapped to
/// `LicenseError::Platform` to match the licensing
/// module's error model.
pub(crate) fn entry_for_pub(user: &str) -> Result<std::sync::Arc<keyring::Entry>, LicenseError> {
    entry_for(user)
}

/// Save the license key string to the keychain. Overwrites any
/// existing license. Returns `Ok(())` on success.
pub fn save_license(key: &str) -> Result<(), LicenseError> {
    let entry = entry_for(KEYCHAIN_USER_LICENSE)?;
    entry.set_password(key)?;
    Ok(())
}

/// Read the license key string from the keychain. Returns
/// `Ok(None)` if no license is stored.
pub fn load_license() -> Result<Option<String>, LicenseError> {
    let entry = entry_for(KEYCHAIN_USER_LICENSE)?;
    match entry.get_password() {
        Ok(k) => Ok(Some(k)),
        Err(keyring::Error::NoEntry) => Ok(None),
        Err(e) => Err(LicenseError::from(e)),
    }
}

/// Delete the license from the keychain. Idempotent.
pub fn delete_license() -> Result<(), LicenseError> {
    let entry = entry_for(KEYCHAIN_USER_LICENSE)?;
    match entry.delete_credential() {
        Ok(()) => Ok(()),
        Err(keyring::Error::NoEntry) => Ok(()),
        Err(e) => Err(LicenseError::from(e)),
    }
}

// --- Tauri command surface ---------------------------------------

/// Tauri command: read the current license status. If the
/// keychain is empty, generate a 14-day trial and return
/// `Trial`. If the keychain has a license but it fails
/// verification, return `Invalid` with the reason. If the
/// keychain has a license that verifies but the machine
/// fingerprint doesn't match, return `Invalid` with reason
/// `"machine-mismatch"`.
#[tauri::command]
pub fn license_get_status() -> LicenseStatus {
    match get_or_generate_status() {
        Ok(status) => status,
        Err(e) => LicenseStatus::Invalid {
            reason: format!("keychain-error: {e}"),
        },
    }
}

fn get_or_generate_status() -> Result<LicenseStatus, LicenseError> {
    // Try to load an existing license. If absent, generate a
    // trial and store it. If present, verify it.
    match load_license()? {
        None => {
            // No license. Generate a trial.
            let (payload, key) = generate_trial_license()?;
            save_license(&key)?;
            Ok(derive_status(&payload))
        }
        Some(key) => {
            // Verify the existing license.
            let payload = match verify_license(&key) {
                Ok(p) => p,
                Err(e) => {
                    return Ok(LicenseStatus::Invalid {
                        reason: format!("verification-failed: {e}"),
                    });
                }
            };
            // Check machine fingerprint.
            let this_machine = machine_fingerprint();
            if payload.sub != this_machine {
                return Ok(LicenseStatus::Invalid {
                    reason: format!("machine-mismatch: bound to a different machine"),
                });
            }
            Ok(derive_status(&payload))
        }
    }
}

/// Tauri command: activate a license. The key is parsed +
/// verified; on success, it's saved to the keychain and the
/// resulting `LicenseStatus` is returned. On failure, an
/// `Invalid` status with the reason is returned (the
/// keychain is NOT modified).
#[tauri::command]
pub fn license_activate(key: String) -> LicenseStatus {
    let trimmed = key.trim();
    if trimmed.is_empty() {
        return LicenseStatus::Invalid {
            reason: "empty key".to_string(),
        };
    }
    let payload = match verify_license(trimmed) {
        Ok(p) => p,
        Err(e) => {
            return LicenseStatus::Invalid {
                reason: format!("verification-failed: {e}"),
            };
        }
    };
    let this_machine = machine_fingerprint();
    if payload.sub != this_machine {
        return LicenseStatus::Invalid {
            reason: "machine-mismatch: bound to a different machine".to_string(),
        };
    }
    if let Err(e) = save_license(trimmed) {
        return LicenseStatus::Invalid {
            reason: format!("keychain-save-failed: {e}"),
        };
    }
    derive_status(&payload)
}

/// Tauri command: deactivate (delete) the current license.
/// Returns the resulting status (which is `Unactivated` after
/// deletion). The next `license_get_status` call will
/// generate a fresh trial.
#[tauri::command]
pub fn license_deactivate() -> LicenseStatus {
    if let Err(e) = delete_license() {
        return LicenseStatus::Invalid {
            reason: format!("keychain-delete-failed: {e}"),
        };
    }
    LicenseStatus::Unactivated
}

/// Tauri command: return this machine's fingerprint. Used
/// by the activation screen so the user can include it in a
/// "please issue me a license" support email.
#[tauri::command]
pub fn license_get_machine_fingerprint() -> String {
    machine_fingerprint()
}

/// Get the `kid` (key id) of the current
/// license. The UI uses this to determine if
/// the license is IAP-issued (so it can show
/// the "Refresh from IAP" button) vs trial
/// or offline-purchase.
///
/// Phase 4.1 (IAP v1.1 follow-ups). Returns
/// `None` if there is no license in the
/// keychain, or the license fails to
/// verify (the UI treats both cases as
/// "not IAP-issued" and hides the refresh
/// button).
///
/// The function never returns the key
/// material — only the `kid` string (one
/// of `"trial"`, `"offline"`, `"iap-local"`).
#[tauri::command]
pub fn license_get_kid() -> Option<String> {
    let key = match load_license() {
        Ok(Some(k)) => k,
        _ => return None,
    };
    let payload = match verify_license(&key) {
        Ok(p) => p,
        Err(_) => return None,
    };
    payload.kid.or_else(|| Some(KID_TRIAL.to_string()))
}

// --- Tests -------------------------------------------------------
//
// The unit tests install the Mock keychain (per the
// `secrets.rs` pattern) and use the test helper functions
// `sign_payload` (public) and `verify_license` (public) to
// exercise the sign + verify round-trip, the shape validation,
// the expiry / grace / machine-mismatch / not-yet-valid paths,
// and the trial generation.
//
// See `docs/plans/prod-p2-licensing-design.md` "Test plan" for
// the full list of 17 tests. The tests are split into "key
// manipulation" (no keychain) and "keychain integration" (mock
// keychain) groups.

#[cfg(test)]
mod tests {
    use super::*;
    use keyring::mock::MockCredentialBuilder;
    use std::sync::{Mutex, Once, OnceLock};

    static INSTALL_MOCK: Once = Once::new();

    fn install_mock() {
        INSTALL_MOCK.call_once(|| {
            let _ = keyring::set_default_credential_builder(Box::new(MockCredentialBuilder {}));
        });
    }

    /// Global lock for tests that touch the mock keychain.
    /// The mock store is per-`Entry` and the entry cache
    /// is process-wide, so two tests running in parallel
    /// that both use the `license` user would collide.
    /// Cargo runs tests in parallel by default; the lock
    /// serializes them. Tests that don't touch the
    /// keychain (the `parse_key`, `sign_payload`, and
    /// `derive_status_at` tests) can run in parallel and
    /// don't acquire the lock.
    fn test_lock() -> &'static Mutex<()> {
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        LOCK.get_or_init(|| Mutex::new(()))
    }

    /// A test secret key. Ed25519 signing keys are 32 bytes;
    /// we use a deterministic test key for reproducibility.
    fn test_key() -> [u8; 32] {
        let mut k = [0u8; 32];
        for (i, b) in k.iter_mut().enumerate() {
            *b = i as u8;
        }
        k
    }

    /// A test pubkey (derived from the test secret). We don't
    /// actually verify against this in every test (most tests
    /// use the trial or production embedded pubkey), but it's
    /// here for the round-trip test.
    fn test_pubkey() -> [u8; 32] {
        let secret = SigningKey::from_bytes(&test_key());
        secret.verifying_key().to_bytes()
    }

    fn sample_payload(plan: &str, iat: i64, exp: i64, sub: &str) -> LicensePayload {
        LicensePayload {
            format: LICENSE_FORMAT_V1.to_string(),
            plan: plan.to_string(),
            iat,
            nbf: iat,
            exp,
            sub: sub.to_string(),
            jti: "0123456789abcdef".to_string(),
            kid: Some(KID_TRIAL.to_string()),
        }
    }

    fn sample_fingerprint() -> String {
        "a".repeat(64) // 64 hex chars (SHA-256 hex)
    }

    // ---- Key manipulation (no keychain) -----------------------

    #[test]
    fn sign_then_verify_roundtrip() {
        let payload = sample_payload(
            PLAN_YEARLY,
            1_000_000,
            1_000_000 + 365 * 86_400,
            &sample_fingerprint(),
        );
        // We sign with the test key, then patch the public
        // key. We can't easily patch the embedded pubkey
        // (it's a const), so we use the trial flow for the
        // round-trip (the trial pubkey is paired with the
        // trial privkey, both embedded).
        let _unused_key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        // The trial plan is required for the trial pubkey
        // branch.
        let mut trial_payload = payload.clone();
        trial_payload.plan = PLAN_TRIAL.to_string();
        let key = sign_payload(&trial_payload, &TRIAL_PRIVKEY).unwrap();
        let verified = verify_license(&key).unwrap();
        assert_eq!(verified, trial_payload);
    }

    #[test]
    fn sign_with_test_key_then_verify_against_test_pubkey_succeeds() {
        // Sign with a test key, parse the key, verify the
        // signature manually using the test pubkey. (We can't
        // `verify_license` because that hard-codes the
        // embedded pubkey, so we use the lower-level `parse_key`
        // + manual ed25519-dalek verification.)
        let payload = sample_payload(
            PLAN_YEARLY,
            1_000_000,
            1_000_000 + 86_400,
            &sample_fingerprint(),
        );
        let key = sign_payload(&payload, &test_key()).unwrap();
        let (parsed, sig_bytes) = parse_key(&key).unwrap();
        assert_eq!(parsed, payload);

        // Manual verify.
        let secret = SigningKey::from_bytes(&test_key());
        let vk = secret.verifying_key();
        let sig = Signature::from_bytes(sig_bytes.as_slice().try_into().unwrap());
        let payload_b64 = key.split('.').nth(1).unwrap();
        let signing_input = format!("{LICENSE_PREFIX}.{payload_b64}");
        vk.verify(signing_input.as_bytes(), &sig).unwrap();
    }

    #[test]
    fn verify_rejects_wrong_signature() {
        let payload = sample_payload(
            PLAN_TRIAL,
            1_000_000,
            1_000_000 + 86_400,
            &sample_fingerprint(),
        );
        let key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        // Mutate one byte of the signature.
        let mut parts: Vec<&str> = key.split('.').collect();
        let sig = parts[2];
        let mut sig_bytes = sig.as_bytes().to_vec();
        // Flip a bit in the first byte (it's base64url; we
        // can't predict the value, but we can flip a
        // character in the encoded form).
        let first = sig_bytes[0];
        sig_bytes[0] = if first == b'A' { b'B' } else { b'A' };
        let new_sig = std::str::from_utf8(&sig_bytes).unwrap();
        parts[2] = new_sig;
        let tampered = parts.join(".");
        let result = verify_license(&tampered);
        assert!(matches!(result, Err(LicenseError::InvalidShape { .. })));
    }

    #[test]
    fn verify_rejects_tampered_payload() {
        let payload = sample_payload(
            PLAN_TRIAL,
            1_000_000,
            1_000_000 + 86_400,
            &sample_fingerprint(),
        );
        let key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        // Re-encode a different payload under the same
        // signature. This is "tamper the payload, keep the
        // signature" — the signature won't match.
        let mut other = payload.clone();
        other.iat = 9_999_999;
        let payload_json = serde_json::to_vec(&other).unwrap();
        let payload_b64 = URL_SAFE_NO_PAD.encode(&payload_json);
        let mut parts: Vec<&str> = key.split('.').collect();
        parts[1] = payload_b64.as_str();
        let tampered = parts.join(".");
        let result = verify_license(&tampered);
        assert!(matches!(result, Err(LicenseError::InvalidShape { .. })));
    }

    #[test]
    fn verify_rejects_malformed_key() {
        let cases = [
            "",
            "not.a.license",
            "LIP1",
            "LIP1.",
            "LIP1.payload",
            "LIP1.payload.signature.extra",
            "XXXX.payload.signature",
            "LIP1.!!!notbase64.signature",
            "LIP1.eyJmb3JtYXQiOiJ4In0.signature", // valid base64, invalid JSON
        ];
        for bad in cases {
            let result = verify_license(bad);
            assert!(
                matches!(result, Err(LicenseError::InvalidShape { .. })),
                "case {bad:?} should reject"
            );
        }
    }

    #[test]
    fn verify_rejects_oversize_fields() {
        let mut payload = sample_payload(
            PLAN_TRIAL,
            1_000_000,
            1_000_000 + 86_400,
            &sample_fingerprint(),
        );
        payload.format = "x".repeat(100);
        let result = sign_payload(&payload, &TRIAL_PRIVKEY);
        // sign_payload doesn't shape-validate, but verify_license
        // does. Build a key from a "pre-validated" payload by
        // bypassing shape validation in sign.
        let _ = result; // shape check happens in parse_key, not sign
                        // Test the shape check directly:
        let shape = payload.validate_shape();
        assert!(matches!(shape, Err(LicenseError::InvalidShape { .. })));

        payload.format = LICENSE_FORMAT_V1.to_string();
        payload.sub = "z".repeat(33); // wrong length
        assert!(matches!(
            payload.validate_shape(),
            Err(LicenseError::InvalidShape { .. })
        ));
        payload.sub = "not-hex".to_string();
        assert!(matches!(
            payload.validate_shape(),
            Err(LicenseError::InvalidShape { .. })
        )); // 7 chars, fails the != 64 check
        payload.sub = "z".repeat(64); // 64 z's
        assert!(matches!(
            payload.validate_shape(),
            Err(LicenseError::InvalidShape { .. })
        )); // 64 non-hex
        payload.sub = "a".repeat(64); // 64 valid hex chars
        assert!(payload.validate_shape().is_ok());
    }

    #[test]
    fn trial_payload_signs_with_trial_key() {
        let (payload, key) = generate_trial_license().unwrap();
        assert_eq!(payload.plan, PLAN_TRIAL);
        let verified = verify_license(&key).unwrap();
        assert_eq!(verified, payload);
    }

    #[test]
    fn machine_fingerprint_is_64_hex_chars() {
        let fp = machine_fingerprint();
        assert_eq!(fp.len(), 64);
        assert!(fp.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn machine_fingerprint_is_stable() {
        let a = machine_fingerprint();
        let b = machine_fingerprint();
        assert_eq!(a, b);
    }

    // ---- Keychain integration (mock keychain) -----------------

    fn reset_keychain() -> std::sync::MutexGuard<'static, ()> {
        install_mock();
        let guard = test_lock().lock().unwrap_or_else(|p| p.into_inner());
        // Use a unique service per test run would be ideal,
        // but we share the global mock store. Clean up by
        // deleting the entries we know about.
        let _ = delete_license();
        guard
    }

    #[test]
    fn status_unactivated_after_deactivate() {
        let _g = reset_keychain();
        // First call generates a trial.
        let s1 = license_get_status();
        assert!(matches!(s1, LicenseStatus::Trial { .. }));
        // Deactivate.
        let s2 = license_deactivate();
        assert_eq!(s2, LicenseStatus::Unactivated);
    }

    #[test]
    fn status_active_after_activation() {
        let _g = reset_keychain();
        // Sign a paid license for the current machine.
        let fp = machine_fingerprint();
        let now = now_unix_secs();
        let payload = sample_payload(PLAN_YEARLY, now, now + 365 * 86_400, &fp);
        // We can't use the embedded production pubkey for
        // verification because the production privkey isn't
        // embedded. So we test the activation path with a
        // trial license (which the app verifies with the
        // trial pubkey).
        let mut trial_payload = payload.clone();
        trial_payload.plan = PLAN_TRIAL.to_string();
        let key = sign_payload(&trial_payload, &TRIAL_PRIVKEY).unwrap();

        // Activate.
        let status = license_activate(key);
        assert!(matches!(status, LicenseStatus::Trial { .. }));
    }

    #[test]
    fn status_grace_after_expiry_within_7_days() {
        let _g = reset_keychain();
        let fp = machine_fingerprint();
        // Sign a trial that's already expired 3 days ago.
        let now = now_unix_secs();
        let payload = sample_payload(PLAN_TRIAL, now - 4 * 86_400, now - 3 * 86_400, &fp);
        let key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        let status = license_activate(key);
        // 3 days into the 7-day grace period.
        match status {
            LicenseStatus::GracePeriod {
                days_into_grace, ..
            } => {
                assert_eq!(days_into_grace, 3);
            }
            other => panic!("expected GracePeriod, got {other:?}"),
        }
    }

    #[test]
    fn status_expired_after_7_days() {
        let _g = reset_keychain();
        let fp = machine_fingerprint();
        // Sign a trial that's expired 8 days ago.
        let now = now_unix_secs();
        let payload = sample_payload(PLAN_TRIAL, now - 9 * 86_400, now - 8 * 86_400, &fp);
        let key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        let status = license_activate(key);
        match status {
            LicenseStatus::Expired { .. } => {}
            other => panic!("expected Expired, got {other:?}"),
        }
    }

    #[test]
    fn deactivate_clears_keychain() {
        let _g = reset_keychain();
        let _ = license_get_status(); // generate trial
        assert!(load_license().unwrap().is_some());
        license_deactivate();
        assert!(load_license().unwrap().is_none());
    }

    #[test]
    fn machine_mismatch_returns_invalid() {
        let _g = reset_keychain();
        // Sign a trial for a DIFFERENT machine. The
        // fingerprint is 64 hex chars (SHA-256 hex of
        // hostname||username||mac).
        let other_fp = "0123456789abcdef".repeat(4);
        assert_eq!(other_fp.len(), 64);
        let now = now_unix_secs();
        let payload = sample_payload(PLAN_TRIAL, now, now + 86_400, &other_fp);
        let key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        let status = license_activate(key);
        match status {
            LicenseStatus::Invalid { reason } => {
                assert!(reason.contains("machine-mismatch"), "reason was: {reason}");
            }
            other => panic!("expected Invalid, got {other:?}"),
        }
    }

    #[test]
    fn empty_key_returns_invalid() {
        let _g = reset_keychain();
        let status = license_activate("".to_string());
        assert!(matches!(status, LicenseStatus::Invalid { .. }));
        let status = license_activate("   ".to_string());
        assert!(matches!(status, LicenseStatus::Invalid { .. }));
    }

    #[test]
    fn tampered_keychain_entry_returns_unactivated_on_next_get() {
        let _g = reset_keychain();
        // Save a bogus license directly to the keychain.
        save_license("LIP1.aaaa.bbbb").unwrap();
        let status = license_get_status();
        // The bogus key fails verification, so the status
        // returns Invalid (not Unactivated — the keychain has
        // something, it's just invalid).
        match status {
            LicenseStatus::Invalid { reason } => {
                assert!(
                    reason.contains("verification-failed"),
                    "reason was: {reason}"
                );
            }
            other => panic!("expected Invalid, got {other:?}"),
        }
    }

    #[test]
    fn not_yet_valid_license_returns_invalid() {
        let _g = reset_keychain();
        let fp = machine_fingerprint();
        let now = now_unix_secs();
        // nbf in the future.
        let payload = sample_payload(PLAN_TRIAL, now, now + 7 * 86_400, &fp);
        let mut payload = payload;
        payload.nbf = now + 3600;
        let key = sign_payload(&payload, &TRIAL_PRIVKEY).unwrap();
        // The shape validation passes (nbf just has to be
        // <= exp, which it is), so verify_license returns Ok.
        // The status derivation is what catches nbf > now.
        let status = license_activate(key);
        match status {
            LicenseStatus::Invalid { reason } => {
                assert!(reason.contains("not-yet-valid"), "reason was: {reason}");
            }
            other => panic!("expected Invalid, got {other:?}"),
        }
    }

    #[test]
    fn derive_status_handles_all_paths() {
        let now = 1_000_000;
        let fp = "a".repeat(32);

        // Active trial, far future exp.
        let p = sample_payload(PLAN_TRIAL, now - 100, now + 86_400, &fp);
        assert!(matches!(
            derive_status_at(&p, now),
            LicenseStatus::Trial { .. }
        ));

        // Active yearly, far future exp.
        let p = sample_payload(PLAN_YEARLY, now - 100, now + 365 * 86_400, &fp);
        assert!(matches!(
            derive_status_at(&p, now),
            LicenseStatus::Active { .. }
        ));

        // Grace period, 1 day past exp.
        let p = sample_payload(PLAN_YEARLY, now - 10 * 86_400, now - 86_400, &fp);
        assert!(matches!(
            derive_status_at(&p, now),
            LicenseStatus::GracePeriod { .. }
        ));

        // Grace period, exactly at boundary.
        let p = sample_payload(PLAN_YEARLY, now - 8 * 86_400, now - GRACE_PERIOD_SECS, &fp);
        match derive_status_at(&p, now) {
            LicenseStatus::GracePeriod { .. } => {}
            other => panic!("expected GracePeriod at boundary, got {other:?}"),
        }

        // Expired, 8 days past exp.
        let p = sample_payload(PLAN_YEARLY, now - 16 * 86_400, now - 8 * 86_400, &fp);
        assert!(matches!(
            derive_status_at(&p, now),
            LicenseStatus::Expired { .. }
        ));

        // Not yet valid.
        let p = sample_payload(PLAN_YEARLY, now, now + 365 * 86_400, &fp);
        let mut p = p;
        p.nbf = now + 3600;
        assert!(matches!(
            derive_status_at(&p, now),
            LicenseStatus::Invalid { .. }
        ));
    }

    #[test]
    fn format_constant_matches_design() {
        // Belt-and-suspenders: the magic prefix and format
        // string are referenced by the design doc; if they
        // ever change, the design doc needs to change too.
        assert_eq!(LICENSE_PREFIX, "LIP1");
        assert_eq!(LICENSE_FORMAT_V1, "lipi-license-v1");
        assert_eq!(PLAN_TRIAL, "trial");
        assert_eq!(PLAN_MONTHLY, "monthly");
        assert_eq!(PLAN_YEARLY, "yearly");
        assert_eq!(GRACE_PERIOD_SECS, 7 * 24 * 60 * 60);
        assert_eq!(TRIAL_DURATION_SECS, 14 * 24 * 60 * 60);
    }

    #[test]
    fn test_pubkey_is_well_formed() {
        // Sanity check that the test pubkey is a valid
        // Ed25519 point. (We don't actually use it for
        // verification — `verify_license` hard-codes the
        // embedded pubkeys — but the function exists for
        // future tests.)
        let _ = VerifyingKey::from_bytes(&test_pubkey()).unwrap();
    }
}
